#!/usr/bin/python3

import doomrl
import os
import readline
import shutil  # for get_terminal_size
import sys
import syslog

from os.path import exists
from syslog import syslog as log

# DoomRL loads score.wad and player.wad on startup, holds them in memory for its
# entire run, and writes them out on exit.
# Score.wad is a gzipped XML file containing the scores. It starts with a CRC,
# and if this CRC is incorrect, will attempt to restore score.wad from backup
# or, failing that, erase it and start over. So merging score.wad is a no-go
# unless we can reverse engineer the CRC. It looks the right size to be md5.

def resetTerm():
  # 'tput reset' on xterm sends this:
  # '\x1Bc\x1B[!p\x1B[?3;4l\x1B[4l\x1B>'
  # ESC c        : full reset
  # CSI ! p      : soft terminal reset
  # CSI ? 3;4 l  : 80 column mode; fast scrolling
  # CSI 4 l      : reset replace mode
  # ESC >        : normal keypad mode
  # Of these we probably only need the first two.
  os.write(1, '\x1Bc\x1B[!p'.encode('ascii'))

def resetTerm():
  os.write(1, '\x1Bc\x1B[!p'.encode('ascii'))

# from commands import Command
# from commands import RegisterCommand

from commands import argsplit, run_command

def sighup(sig, frame):
  """Signal handler for SIGHUP, which is raised when the user disconnects suddenly."""
  # TODO: clean up half-created user directories.

  if doomrl.user():
    # If we got interrupted while the player was actually in DoomRL, there's a
    # ttyrec file. We could try recovering it, but DoomRL's crash recovery is
    # so unreliable that we probably can't match it up to a save file or
    # scoreline, so we might as well just delete it.
    try:
      os.remove(doomrl.home('ttyrec'))
    except:
      pass


def main():
  from signal import signal,SIGHUP
  signal(SIGHUP, sighup)

  syslog.openlog('doomrl-server', facility=syslog.LOG_DAEMON)

  if exists(doomrl.path('motd')):
    print(open(doomrl.path('motd')).read())
  else:
    print(open(doomrl.path('motd.default')).read())

  (cols, rows) = shutil.get_terminal_size()
  min_rows = 26 if exists(doomrl.path('ttysound', 'libSDL_mixer-1.2.so.0')) else 25
  if int(rows) == 0 and int(cols) == 0:
    print("Warning: couldn't detect terminal size. Please make sure your terminal"
          " is at least 80x%d or the game will not display correctly." % min_rows)
  elif int(rows) < min_rows or int(cols) < 80:
    print("Warning: your terminal size (%sx%s) is smaller than the 80x%d"
          " needed by DoomRL. The game will not display correctly."
          % (cols, rows, min_rows))

  while True:
    try:
      if exists(doomrl.path('maintenance')):
        print(open(doomrl.path('maintenance')).read())
        sys.exit(0)
      [cmd, args] = argsplit(input('\n%s> ' % (doomrl.user() or 'guest')).strip())
      if not cmd:
        pass
      elif cmd == 'quit' or cmd == 'exit':
        break
      else:
        run_command(cmd, args)
    except EOFError as e:
      break
    except KeyboardInterrupt:
      pass
    except Exception as e:
      import traceback
      log('Unhandled exception in mainloop: ' + traceback.format_exc())
      resetTerm()
      print('\rError in mainloop: %s' % str(e))
      traceback.print_exc()

  if doomrl.user():
    log('User %s logged out.' % doomrl.user())
  print('Goodbye!')

if __name__ == '__main__':
  main()
