[package]
name = "ttysound"
version = "0.1.0"
authors = ["Ben Kelly <bk@ancilla.ca>"]

[lib]
name = "ttysound"
path = "src/libttysound.rs"
crate-type = ["dylib"]

[dependencies]
libc="*"
time="*"
lazy_static="0.1.11"
